[project]
name = "postcodes"
version = "0.1.0"
description = "Processes Cartociudad addresses to produce a list of postcodes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fiona>=1.10.1",
    "pyproj>=3.6.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
]
