[project]
name = "dcac-postcodes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fiona>=1.10.1",
    "pyproj>=3.6.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
]
