services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5678:5678"  # Debug port
    entrypoint: python3
    # command: -m debugpy --listen 0.0.0.0:5678 --wait-for-client src/main.py ${LOCAL_MODE:+--local}
    command: src/main.py ${LOCAL_MODE:+--local}
